import type { Scheme } from "./schemeseva-types";

export const localSchemes: Scheme[] = [
    {
        id: "pm-kisan-001",
        schemeName: "PM-KISAN Samman Nidhi",
        ministry: "Ministry of Agriculture & Farmers Welfare",
        benefitType: "cash",
        benefitAmount: "Rs 6,000/year in 3 instalments",
        description: "Income support to landholding farmer families across India.",
        eligibility: { occupations: ["farmer"], requiresAadhaar: true, requiresBankAccount: true },
        keywords: ["farmer", "land", "agriculture", "income support", "pm kisan"],
        documentsRequired: ["Aadhaar", "Land records", "Bank account", "Ration card"],
        applicationSteps: ["Visit pmkisan.gov.in", "Complete farmer registration", "Submit Aadhaar, land, and bank details", "Track status online"],
        applicationUrl: "https://pmkisan.gov.in",
        applicationMode: "online",
        sourceUrl: "https://pmkisan.gov.in",
        lastVerified: "2026-06-15",
        stateScope: "central",
    },
    {
        id: "rythu-bandhu-ts-013",
        schemeName: "Rythu Bandhu - Telangana",
        ministry: "Government of Telangana",
        benefitType: "cash",
        benefitAmount: "Rs 10,000/acre/year",
        description: "Investment support to Telangana farmers per acre owned.",
        eligibility: { occupations: ["farmer"], states: ["telangana"], requiresAadhaar: true, requiresBankAccount: true },
        keywords: ["farmer", "telangana", "rythu", "investment", "kharif", "rabi"],
        documentsRequired: ["Pattadar passbook", "Aadhaar", "Bank passbook"],
        applicationSteps: ["Meet the Village Revenue Officer with land records", "Verify ownership in RoR records", "Confirm bank details", "Track updates on the official portal"],
        applicationUrl: "https://rythubandhu.telangana.gov.in",
        applicationMode: "offline",
        sourceUrl: "https://rythubandhu.telangana.gov.in",
        lastVerified: "2026-06-15",
        stateScope: "telangana",
    },
    {
        id: "rythu-bima-ts-014",
        schemeName: "Rythu Bima - Telangana",
        ministry: "Government of Telangana",
        benefitType: "insurance",
        benefitAmount: "Rs 5,00,000 life cover",
        description: "Life insurance cover for eligible Telangana farmers aged 18 to 59.",
        eligibility: { occupations: ["farmer"], states: ["telangana"], minAge: 18, maxAge: 59, requiresBankAccount: true },
        keywords: ["farmer", "insurance", "telangana", "life insurance", "rythu bima"],
        documentsRequired: ["Aadhaar", "Pattadar passbook", "Nominee details"],
        applicationSteps: ["Confirm enrolment through local agriculture officials", "Submit nominee details", "Keep bank and land records updated"],
        applicationUrl: "https://rythubima.telangana.gov.in",
        applicationMode: "offline",
        sourceUrl: "https://rythubima.telangana.gov.in",
        lastVerified: "2026-06-15",
        stateScope: "telangana",
    },
    {
        id: "kcc-002",
        schemeName: "Kisan Credit Card",
        ministry: "Ministry of Agriculture",
        benefitType: "loan",
        benefitAmount: "Up to Rs 3,00,000 at subsidised interest",
        description: "Short-term credit for crop production and allied activities.",
        eligibility: { occupations: ["farmer"], requiresAadhaar: true, requiresBankAccount: true },
        keywords: ["farmer", "credit", "loan", "crop", "kcc"],
        documentsRequired: ["Aadhaar", "Land records", "Bank account", "Passport photo"],
        applicationSteps: ["Visit a nearby bank branch", "Ask for Kisan Credit Card form", "Submit land and identity documents", "Complete bank verification"],
        applicationUrl: "https://www.myscheme.gov.in/schemes/kcc",
        applicationMode: "offline",
        sourceUrl: "https://www.myscheme.gov.in/schemes/kcc",
        lastVerified: "2026-05-20",
        stateScope: "central",
    },
    {
        id: "pmfby-003",
        schemeName: "Pradhan Mantri Fasal Bima Yojana",
        ministry: "Ministry of Agriculture",
        benefitType: "insurance",
        benefitAmount: "Crop insurance coverage varies by crop and area",
        description: "Crop insurance against natural calamities, pests, and disease.",
        eligibility: { occupations: ["farmer"], requiresAadhaar: true, requiresBankAccount: true },
        keywords: ["farmer", "crop", "insurance", "fasal bima", "agriculture"],
        documentsRequired: ["Aadhaar", "Land records", "Bank account", "Crop sowing certificate"],
        applicationSteps: ["Visit pmfby.gov.in or a bank", "Choose season and crop", "Submit land and crop details", "Pay farmer premium if applicable"],
        applicationUrl: "https://pmfby.gov.in",
        applicationMode: "both",
        sourceUrl: "https://pmfby.gov.in",
        lastVerified: "2026-06-01",
        stateScope: "central",
    },
    {
        id: "mudra-006",
        schemeName: "Pradhan Mantri Mudra Yojana",
        ministry: "Ministry of Finance",
        benefitType: "loan",
        benefitAmount: "Shishu Rs 50k / Kishore Rs 5L / Tarun Rs 10L",
        description: "Collateral-free micro-loans for non-farm micro-enterprises.",
        eligibility: { minAge: 18, occupations: ["entrepreneur", "small business", "self-employed", "tailoring", "tiffin"] },
        keywords: ["loan", "business", "entrepreneur", "mudra", "micro loan", "startup", "tiffin", "shop", "tailoring"],
        documentsRequired: ["Aadhaar", "PAN", "Business proof", "Bank statement", "Passport photo"],
        applicationSteps: ["Approach any bank, MFI, or NBFC", "Fill Mudra loan form", "Submit basic business plan", "Complete lender verification"],
        applicationUrl: "https://www.mudra.org.in",
        applicationMode: "both",
        sourceUrl: "https://www.mudra.org.in",
        lastVerified: "2026-06-10",
        stateScope: "central",
    },
    {
        id: "ts-fee-reimbursement-021",
        schemeName: "Telangana Fee Reimbursement",
        ministry: "Government of Telangana",
        benefitType: "scholarship",
        benefitAmount: "Tuition fee reimbursement as per course rules",
        description: "Fee reimbursement support for eligible Telangana students from reserved and low-income categories.",
        eligibility: { occupations: ["student"], states: ["telangana"], categories: ["sc", "st", "obc", "ebc", "minority"], maxAnnualIncome: 200000, requiresAadhaar: true, requiresBankAccount: true },
        keywords: ["student", "scholarship", "fee reimbursement", "telangana", "college", "engineering"],
        documentsRequired: ["Aadhaar", "Income certificate", "Caste/category certificate", "Bonafide certificate", "Bank account"],
        applicationSteps: ["Visit Telangana ePASS portal", "Register student details", "Upload income and category documents", "Submit through college verification"],
        applicationUrl: "https://telanganaepass.cgg.gov.in",
        applicationMode: "online",
        sourceUrl: "https://telanganaepass.cgg.gov.in",
        lastVerified: "2026-06-20",
        stateScope: "telangana",
    },
    {
        id: "aasara-pension-ts-025",
        schemeName: "Aasara Pension - Telangana",
        ministry: "Government of Telangana",
        benefitType: "pension",
        benefitAmount: "Monthly pension as per category",
        description: "Social security pension for elderly, widows, disabled citizens, and other eligible groups in Telangana.",
        eligibility: { states: ["telangana"], maxAnnualIncome: 150000, requiresAadhaar: true, requiresBankAccount: true },
        keywords: ["pension", "elderly", "widow", "disabled", "telangana", "aasara"],
        documentsRequired: ["Aadhaar", "Age proof", "Income certificate", "Bank account", "Category proof if applicable"],
        applicationSteps: ["Apply at local MeeSeva or municipal office", "Submit identity, income, and bank documents", "Complete field verification", "Track status through local office"],
        applicationUrl: "https://www.telangana.gov.in",
        applicationMode: "offline",
        sourceUrl: "https://www.telangana.gov.in",
        lastVerified: "2026-06-20",
        stateScope: "telangana",
    },
];
