import type { Scheme } from "./schemeseva-types";

const VERIFIED_ON = "2026-07-09";

export const localSchemes: Scheme[] = [
  {
    id: "pm-kisan-001",
    schemeName: "PM-KISAN Samman Nidhi",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    benefitType: "cash",
    benefitAmount: "Rs 6,000/year in 3 instalments",
    description: "Income support to eligible landholding farmer families across India.",
    eligibility: { occupations: ["farmer"], requiresAadhaar: true, requiresBankAccount: true },
    keywords: ["farmer", "land", "agriculture", "income support", "pm kisan"],
    documentsRequired: ["Aadhaar Card", "Land records", "Bank account", "Ration card if available"],
    applicationSteps: [
      "Visit the PM-KISAN portal or a Common Service Centre.",
      "Complete farmer registration with landholding details.",
      "Submit identity, land, and bank documents for verification.",
      "Track payment status on the official portal.",
    ],
    applicationUrl: "https://pmkisan.gov.in",
    applicationMode: "online",
    sourceUrl: "https://pmkisan.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "kcc-002",
    schemeName: "Kisan Credit Card",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    benefitType: "loan",
    benefitAmount: "Short-term agriculture credit; limit varies by bank and crop",
    description: "Credit facility for crop production, animal husbandry, fisheries, and allied farm needs.",
    eligibility: { occupations: ["farmer"], requiresAadhaar: true, requiresBankAccount: true },
    keywords: ["farmer", "credit", "loan", "crop", "kcc", "bank"],
    documentsRequired: ["Aadhaar Card", "Land records", "Bank account", "Passport photo"],
    applicationSteps: [
      "Visit a participating bank branch.",
      "Ask for the Kisan Credit Card application.",
      "Submit land, identity, and bank documents.",
      "Complete bank verification and credit appraisal.",
    ],
    applicationUrl: "https://www.myscheme.gov.in/schemes/kcc",
    applicationMode: "offline",
    sourceUrl: "https://www.myscheme.gov.in/schemes/kcc",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "pmfby-003",
    schemeName: "Pradhan Mantri Fasal Bima Yojana",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    benefitType: "insurance",
    benefitAmount: "Crop insurance coverage varies by crop, season, and notified area",
    description: "Crop insurance for notified crops against natural calamities, pests, and disease.",
    eligibility: { occupations: ["farmer"], requiresAadhaar: true, requiresBankAccount: true },
    keywords: ["farmer", "crop", "insurance", "fasal bima", "agriculture"],
    documentsRequired: ["Aadhaar Card", "Land records", "Bank account", "Crop sowing certificate"],
    applicationSteps: [
      "Visit the PMFBY portal, bank, CSC, or insurance channel.",
      "Choose the relevant season, crop, and notified area.",
      "Submit land and crop sowing details.",
      "Pay the farmer premium if applicable and keep the receipt.",
    ],
    applicationUrl: "https://pmfby.gov.in",
    applicationMode: "both",
    sourceUrl: "https://pmfby.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "pm-kusum-004",
    schemeName: "PM-KUSUM",
    ministry: "Ministry of New and Renewable Energy",
    benefitType: "subsidy",
    benefitAmount: "Solar pump or solarization support; subsidy share varies by component/state",
    description: "Support for farmers to install standalone solar pumps or solarize grid-connected pumps.",
    eligibility: { occupations: ["farmer"], requiresAadhaar: true, requiresBankAccount: true },
    keywords: ["farmer", "solar", "pump", "irrigation", "kusum", "renewable energy"],
    documentsRequired: ["Aadhaar Card", "Land records", "Bank account", "Pump or electricity connection details"],
    applicationSteps: [
      "Check the PM-KUSUM portal and state renewable energy agency instructions.",
      "Select the relevant component for solar pump or pump solarization.",
      "Submit land, identity, and pump details.",
      "Complete state agency or DISCOM verification before installation.",
    ],
    applicationUrl: "https://pmkusum.mnre.gov.in/landing.html",
    applicationMode: "both",
    sourceUrl: "https://pmkusum.mnre.gov.in/landing.html",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "soil-health-card-005",
    schemeName: "Soil Health Card Scheme",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    benefitType: "advisory",
    benefitAmount: "Soil testing and crop-wise nutrient recommendations",
    description: "Soil testing support that gives farmers recommendations for balanced fertilizer use.",
    eligibility: { occupations: ["farmer"] },
    keywords: ["farmer", "soil", "fertilizer", "crop", "agriculture", "soil health"],
    documentsRequired: ["Farmer identity proof", "Land details", "Soil sample details"],
    applicationSteps: [
      "Contact the local agriculture office or soil testing facility.",
      "Provide farm and crop details.",
      "Submit soil samples as instructed.",
      "Use the official portal or local office to access recommendations.",
    ],
    applicationUrl: "https://soilhealth.dac.gov.in",
    applicationMode: "both",
    sourceUrl: "https://soilhealth.dac.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "mudra-006",
    schemeName: "Pradhan Mantri Mudra Yojana",
    ministry: "Ministry of Finance",
    benefitType: "loan",
    benefitAmount: "Shishu, Kishor, and Tarun loans; amount varies by business stage",
    description: "Collateral-free micro-enterprise loans through banks, NBFCs, and MFIs.",
    eligibility: {
      minAge: 18,
      occupations: ["entrepreneur", "small business", "self-employed", "tailoring", "tiffin", "artisan"],
    },
    keywords: ["loan", "business", "entrepreneur", "mudra", "micro loan", "startup", "tiffin", "shop", "tailoring"],
    documentsRequired: ["Identity proof", "Address proof", "Business proof", "Bank statement", "Passport photo"],
    applicationSteps: [
      "Approach a bank, NBFC, MFI, or use the official Mudra-linked application channel.",
      "Choose Shishu, Kishor, or Tarun based on business stage.",
      "Submit business and identity documents.",
      "Complete lender appraisal and sanction process.",
    ],
    applicationUrl: "https://www.mudra.org.in",
    applicationMode: "both",
    sourceUrl: "https://www.mudra.org.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "stand-up-india-007",
    schemeName: "Stand-Up India",
    ministry: "Department of Financial Services, Ministry of Finance",
    benefitType: "loan",
    benefitAmount: "Bank loan from Rs 10 lakh to Rs 1 crore for eligible greenfield enterprises",
    description: "Bank loan support for SC/ST and women entrepreneurs setting up greenfield enterprises.",
    eligibility: {
      minAge: 18,
      genders: ["female"],
      occupations: ["entrepreneur", "small business", "self-employed"],
    },
    keywords: ["woman", "female", "entrepreneur", "sc", "st", "business", "stand up india", "loan"],
    documentsRequired: ["Identity proof", "Category proof if applicable", "Business plan", "Bank account", "Project documents"],
    applicationSteps: [
      "Visit the Stand-Up India portal or a bank branch.",
      "Register borrower and enterprise details.",
      "Prepare a greenfield business proposal.",
      "Complete handholding and bank appraisal.",
    ],
    applicationUrl: "https://www.standupmitra.in",
    applicationMode: "both",
    sourceUrl: "https://www.standupmitra.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "pm-svanidhi-008",
    schemeName: "PM SVANidhi",
    ministry: "Ministry of Housing and Urban Affairs",
    benefitType: "loan",
    benefitAmount: "Working capital loan support for eligible street vendors; amount increases by repayment cycle",
    description: "Working capital credit and digital transaction incentives for eligible street vendors.",
    eligibility: {
      occupations: ["street vendor", "vendor", "small business", "self-employed", "entrepreneur"],
      requiresBankAccount: true,
    },
    keywords: ["street vendor", "vendor", "urban", "loan", "working capital", "svanidhi", "small business"],
    documentsRequired: ["Certificate of vending or Letter of Recommendation", "Identity proof", "Bank account", "Mobile number"],
    applicationSteps: [
      "Visit the PM SVANidhi portal or approach the urban local body.",
      "Verify vending certificate or obtain a Letter of Recommendation if eligible.",
      "Submit bank and identity details.",
      "Complete lender verification and loan processing.",
    ],
    applicationUrl: "https://pmsvanidhi.mohua.gov.in",
    applicationMode: "online",
    sourceUrl: "https://pmsvanidhi.mohua.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "pmkvy-009",
    schemeName: "Pradhan Mantri Kaushal Vikas Yojana",
    ministry: "Ministry of Skill Development and Entrepreneurship",
    benefitType: "training",
    benefitAmount: "Skill training and certification support; benefits vary by course",
    description: "Skill training and certification programme for youth and workers seeking better livelihoods.",
    eligibility: {
      minAge: 15,
      occupations: ["unemployed", "student", "self-employed", "worker"],
    },
    keywords: ["skill", "training", "unemployed", "youth", "student", "job", "pmkvy"],
    documentsRequired: ["Identity proof", "Age proof", "Education details", "Mobile number"],
    applicationSteps: [
      "Check available courses through Skill India or PMKVY channels.",
      "Choose a training centre or course aligned to your goal.",
      "Register with identity and education details.",
      "Attend training and complete assessment for certification.",
    ],
    applicationUrl: "https://www.pmkvyofficial.org",
    applicationMode: "online",
    sourceUrl: "https://www.pmkvyofficial.org",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "nsp-scholarship-010",
    schemeName: "National Scholarship Portal Scholarships",
    ministry: "Government of India",
    benefitType: "scholarship",
    benefitAmount: "Scholarship amount varies by ministry, course, and category",
    description: "Common national portal for applying to eligible central scholarship schemes.",
    eligibility: {
      occupations: ["student"],
      maxAnnualIncome: 250000,
      requiresAadhaar: true,
      requiresBankAccount: true,
    },
    keywords: ["student", "scholarship", "nsp", "college", "education", "post matric"],
    documentsRequired: ["Aadhaar Card or enrolment details", "Income certificate", "Caste/category certificate if applicable", "Bonafide certificate", "Bank account"],
    applicationSteps: [
      "Visit the National Scholarship Portal.",
      "Complete One Time Registration if required.",
      "Select the scholarship that matches your category and course.",
      "Submit documents and track verification by institute and department.",
    ],
    applicationUrl: "https://scholarships.gov.in",
    applicationMode: "online",
    sourceUrl: "https://scholarships.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "pmay-g-011",
    schemeName: "Pradhan Mantri Awaas Yojana - Gramin",
    ministry: "Ministry of Rural Development",
    benefitType: "housing",
    benefitAmount: "Rural housing assistance as per PMAY-G rules",
    description: "Housing assistance for eligible rural households identified through official surveys and lists.",
    eligibility: { maxAnnualIncome: 300000 },
    keywords: ["housing", "home", "rural", "bpl", "poor", "awas", "pmay"],
    documentsRequired: ["Identity proof", "Bank account", "Job card or household verification if applicable", "Local body verification"],
    applicationSteps: [
      "Check eligibility through Gram Panchayat or PMAY-G/Awaas+ process.",
      "Confirm household details in the official list or survey.",
      "Submit bank and identity documents.",
      "Track sanction and instalments through official channels.",
    ],
    applicationUrl: "https://pmayg.nic.in",
    applicationMode: "both",
    sourceUrl: "https://pmayg.nic.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "pmjay-012",
    schemeName: "Ayushman Bharat PM-JAY",
    ministry: "National Health Authority, Ministry of Health and Family Welfare",
    benefitType: "health",
    benefitAmount: "Health cover up to Rs 5 lakh per eligible family per year",
    description: "Cashless hospital treatment support for eligible families at empanelled hospitals.",
    eligibility: { maxAnnualIncome: 250000 },
    keywords: ["health", "hospital", "insurance", "pmjay", "ayushman", "bpl", "poor"],
    documentsRequired: ["Identity proof", "Ration card or family document", "Eligibility verification document", "Mobile number"],
    applicationSteps: [
      "Check eligibility on the PM-JAY or National Health Authority channel.",
      "Visit an empanelled hospital or Ayushman help desk.",
      "Complete identity and family verification.",
      "Use cashless treatment only after official approval.",
    ],
    applicationUrl: "https://www.pmjay.gov.in",
    applicationMode: "both",
    sourceUrl: "https://www.pmjay.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "pmjdy-013",
    schemeName: "Pradhan Mantri Jan Dhan Yojana",
    ministry: "Department of Financial Services, Ministry of Finance",
    benefitType: "financial-inclusion",
    benefitAmount: "Basic bank account and linked financial inclusion benefits",
    description: "Financial inclusion scheme for opening basic savings bank accounts and accessing banking services.",
    eligibility: { minAge: 10 },
    keywords: ["bank", "account", "financial inclusion", "jan dhan", "rupay", "savings"],
    documentsRequired: ["Identity proof", "Address proof", "Passport photo if required by bank"],
    applicationSteps: [
      "Visit a bank branch or Bank Mitra.",
      "Ask for a Basic Savings Bank Deposit Account under PMJDY.",
      "Submit identity and address documents.",
      "Collect account details and RuPay card if issued.",
    ],
    applicationUrl: "https://www.pmjdy.gov.in",
    applicationMode: "offline",
    sourceUrl: "https://www.pmjdy.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "pmjjby-014",
    schemeName: "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    ministry: "Department of Financial Services, Ministry of Finance",
    benefitType: "insurance",
    benefitAmount: "Rs 2 lakh life insurance cover; annual premium as notified",
    description: "One-year renewable life insurance cover through participating banks and post offices.",
    eligibility: { minAge: 18, maxAge: 50, requiresBankAccount: true },
    keywords: ["insurance", "life cover", "bank", "pmjjby", "financial security"],
    documentsRequired: ["Bank or post office account", "Consent for auto-debit", "Identity proof"],
    applicationSteps: [
      "Contact your bank or post office.",
      "Submit consent for auto-debit of premium.",
      "Complete enrolment within the permitted period.",
      "Renew annually as per scheme rules.",
    ],
    applicationUrl: "https://financialservices.gov.in/beta/en/pmjjby",
    applicationMode: "offline",
    sourceUrl: "https://financialservices.gov.in/beta/en/pmjjby",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "pmsby-015",
    schemeName: "Pradhan Mantri Suraksha Bima Yojana",
    ministry: "Department of Financial Services, Ministry of Finance",
    benefitType: "insurance",
    benefitAmount: "Accident insurance cover up to Rs 2 lakh; annual premium as notified",
    description: "One-year renewable accident insurance cover through participating banks and post offices.",
    eligibility: { minAge: 18, maxAge: 70, requiresBankAccount: true },
    keywords: ["insurance", "accident", "bank", "pmsby", "financial security"],
    documentsRequired: ["Bank or post office account", "Consent for auto-debit", "Identity proof"],
    applicationSteps: [
      "Contact your bank or post office.",
      "Submit PMSBY enrolment and auto-debit consent.",
      "Confirm nominee details if required.",
      "Renew annually as per scheme rules.",
    ],
    applicationUrl: "https://financialservices.gov.in/beta/en/pmsby",
    applicationMode: "offline",
    sourceUrl: "https://financialservices.gov.in/beta/en/pmsby",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "apy-016",
    schemeName: "Atal Pension Yojana",
    ministry: "Pension Fund Regulatory and Development Authority",
    benefitType: "pension",
    benefitAmount: "Guaranteed pension slab from Rs 1,000 to Rs 5,000/month after 60, based on contribution",
    description: "Voluntary pension scheme for eligible bank account holders in the unorganised sector.",
    eligibility: { minAge: 18, maxAge: 40, requiresBankAccount: true },
    keywords: ["pension", "unorganised", "bank", "atal pension", "apy", "retirement"],
    documentsRequired: ["Bank account", "Mobile number", "Identity proof"],
    applicationSteps: [
      "Contact a bank branch or digital APY enrolment channel.",
      "Choose the pension slab and contribution frequency.",
      "Submit identity and bank details.",
      "Maintain contributions until pension age.",
    ],
    applicationUrl: "https://www.npscra.nsdl.co.in/scheme-details.php",
    applicationMode: "both",
    sourceUrl: "https://www.npscra.nsdl.co.in/scheme-details.php",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "sukanya-017",
    schemeName: "Sukanya Samriddhi Account",
    ministry: "Department of Posts, Ministry of Communications",
    benefitType: "savings",
    benefitAmount: "Small savings account for girl child; interest rate notified periodically",
    description: "Government small savings account for a girl child, opened by guardian as per scheme rules.",
    eligibility: { genders: ["female"], maxAge: 10 },
    keywords: ["girl child", "sukanya", "savings", "education", "daughter"],
    documentsRequired: ["Birth certificate of girl child", "Guardian identity proof", "Guardian address proof"],
    applicationSteps: [
      "Visit a post office or authorised bank.",
      "Submit girl child's birth certificate and guardian KYC.",
      "Open the account with the minimum deposit required.",
      "Continue deposits as per small savings rules.",
    ],
    applicationUrl: "https://www.indiapost.gov.in/Financial/Pages/Content/Sukanya-Samriddhi-Account.aspx",
    applicationMode: "offline",
    sourceUrl: "https://www.indiapost.gov.in/Financial/Pages/Content/Sukanya-Samriddhi-Account.aspx",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "nsap-ignoaps-018",
    schemeName: "NSAP - Indira Gandhi National Old Age Pension Scheme",
    ministry: "Ministry of Rural Development",
    benefitType: "pension",
    benefitAmount: "Central social assistance pension; amount varies with state top-up",
    description: "Social assistance pension for older citizens from poor households, implemented with state processes.",
    eligibility: { minAge: 60, maxAnnualIncome: 100000 },
    keywords: ["pension", "elderly", "old age", "nsap", "poor", "senior"],
    documentsRequired: ["Age proof", "Identity proof", "Income or household verification", "Bank account"],
    applicationSteps: [
      "Apply through local Gram Panchayat, municipal body, or state social welfare channel.",
      "Submit age, identity, and income or household verification documents.",
      "Complete field verification if required.",
      "Track pension sanction through local office or NSAP/state portal.",
    ],
    applicationUrl: "https://nsap.nic.in",
    applicationMode: "both",
    sourceUrl: "https://nsap.nic.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "central",
  },
  {
    id: "rythu-bandhu-ts-019",
    schemeName: "Rythu Bandhu - Telangana",
    ministry: "Government of Telangana",
    benefitType: "cash",
    benefitAmount: "Investment support per acre/season as notified by Telangana government",
    description: "Investment support to eligible Telangana landholding farmers.",
    eligibility: {
      occupations: ["farmer"],
      states: ["telangana"],
      requiresAadhaar: true,
      requiresBankAccount: true,
    },
    keywords: ["farmer", "telangana", "rythu", "investment", "kharif", "rabi", "land"],
    documentsRequired: ["Pattadar passbook", "Aadhaar Card", "Bank passbook", "Land records"],
    applicationSteps: [
      "Verify land ownership in Telangana land records.",
      "Confirm bank details with local agriculture or revenue officials.",
      "Keep Pattadar passbook and identity documents updated.",
      "Track official government updates for release schedule.",
    ],
    applicationUrl: "https://rythubandhu.telangana.gov.in",
    applicationMode: "offline",
    sourceUrl: "https://rythubandhu.telangana.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
  {
    id: "rythu-bima-ts-020",
    schemeName: "Rythu Bima - Telangana",
    ministry: "Government of Telangana",
    benefitType: "insurance",
    benefitAmount: "Life insurance cover as notified by Telangana government",
    description: "Life insurance cover for eligible Telangana farmers in the notified age range.",
    eligibility: {
      occupations: ["farmer"],
      states: ["telangana"],
      minAge: 18,
      maxAge: 59,
      requiresBankAccount: true,
    },
    keywords: ["farmer", "insurance", "telangana", "life insurance", "rythu bima"],
    documentsRequired: ["Aadhaar Card", "Pattadar passbook", "Bank account", "Nominee details"],
    applicationSteps: [
      "Confirm enrolment through local agriculture officials.",
      "Submit nominee and farmer details.",
      "Keep bank and land records updated.",
      "Use official channels for claim guidance.",
    ],
    applicationUrl: "https://rythubima.telangana.gov.in",
    applicationMode: "offline",
    sourceUrl: "https://rythubima.telangana.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
  {
    id: "ts-fee-reimbursement-021",
    schemeName: "Telangana Fee Reimbursement",
    ministry: "Social Welfare Department, Government of Telangana",
    benefitType: "scholarship",
    benefitAmount: "Tuition fee reimbursement as per course and department rules",
    description: "Fee reimbursement support for eligible Telangana students from reserved and low-income categories.",
    eligibility: {
      occupations: ["student"],
      states: ["telangana"],
      categories: ["sc", "st", "obc", "ebc", "minority"],
      maxAnnualIncome: 200000,
      requiresAadhaar: true,
      requiresBankAccount: true,
    },
    keywords: ["student", "scholarship", "fee reimbursement", "telangana", "college", "engineering", "epass"],
    documentsRequired: ["Aadhaar Card", "Income certificate", "Caste/category certificate", "Bonafide certificate", "Bank account"],
    applicationSteps: [
      "Visit Telangana ePASS portal.",
      "Register or renew student scholarship details.",
      "Upload income, category, and course documents.",
      "Submit through college and department verification.",
    ],
    applicationUrl: "https://telanganaepass.cgg.gov.in",
    applicationMode: "online",
    sourceUrl: "https://telanganaepass.cgg.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
  {
    id: "aasara-pension-ts-022",
    schemeName: "Aasara Pension - Telangana",
    ministry: "Society for Elimination of Rural Poverty, Government of Telangana",
    benefitType: "pension",
    benefitAmount: "Monthly pension as notified by Telangana government and category",
    description: "Social security pension for older citizens, widows, disabled citizens, and other eligible groups in Telangana.",
    eligibility: {
      states: ["telangana"],
      maxAnnualIncome: 150000,
      requiresAadhaar: true,
      requiresBankAccount: true,
    },
    keywords: ["pension", "elderly", "widow", "disabled", "telangana", "aasara", "senior"],
    documentsRequired: ["Aadhaar Card", "Age proof", "Income certificate", "Bank account", "Category proof if applicable"],
    applicationSteps: [
      "Apply through local MeeSeva, municipal, or Panchayat channel.",
      "Submit identity, income, age, and bank documents.",
      "Complete local field verification.",
      "Track sanction through local office or official portal.",
    ],
    applicationUrl: "https://www.aasara.telangana.gov.in/SSPTG/userinterface/portal/loginpage.aspx",
    applicationMode: "offline",
    sourceUrl: "https://www.aasara.telangana.gov.in/SSPTG/userinterface/portal/loginpage.aspx",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
  {
    id: "kalyana-lakshmi-ts-023",
    schemeName: "Kalyana Lakshmi / Shaadi Mubarak - Telangana",
    ministry: "Government of Telangana",
    benefitType: "cash",
    benefitAmount: "Marriage assistance amount as notified by Telangana government",
    description: "Marriage assistance for eligible Telangana brides from low-income households.",
    eligibility: {
      states: ["telangana"],
      genders: ["female"],
      minAge: 18,
      categories: ["sc", "st", "obc", "ebc", "minority"],
      maxAnnualIncome: 200000,
      requiresAadhaar: true,
      requiresBankAccount: true,
    },
    keywords: ["marriage", "bride", "female", "telangana", "kalyana lakshmi", "shaadi mubarak", "minority"],
    documentsRequired: ["Bride identity proof", "Age proof", "Income certificate", "Caste/community certificate", "Bank account"],
    applicationSteps: [
      "Visit Telangana ePASS Kalyana Lakshmi / Shaadi Mubarak service.",
      "Register bride and family details.",
      "Upload age, income, category, and bank documents.",
      "Submit for official verification before/after marriage as applicable.",
    ],
    applicationUrl: "https://telanganaepass.cgg.gov.in/KalyanaLakshmiLinks.jsp",
    applicationMode: "online",
    sourceUrl: "https://telanganaepass.cgg.gov.in/KalyanaLakshmiLinks.jsp",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
  {
    id: "aarogyasri-ts-024",
    schemeName: "Rajiv Aarogyasri - Telangana",
    ministry: "Aarogyasri Health Care Trust, Government of Telangana",
    benefitType: "health",
    benefitAmount: "Cashless treatment support for covered procedures as per trust rules",
    description: "Health coverage for eligible Telangana residents through network hospitals and covered procedures.",
    eligibility: { states: ["telangana"], maxAnnualIncome: 250000 },
    keywords: ["health", "hospital", "aarogyasri", "telangana", "insurance", "treatment"],
    documentsRequired: ["Aarogyasri or family eligibility card if available", "Identity proof", "Residence proof", "Medical records"],
    applicationSteps: [
      "Check eligibility through Aarogyasri help desk, network hospital, or official portal.",
      "Visit a network hospital for covered treatment.",
      "Submit identity and family eligibility details.",
      "Proceed only after hospital/trust authorization.",
    ],
    applicationUrl: "https://www.aarogyasri.telangana.gov.in",
    applicationMode: "both",
    sourceUrl: "https://www.aarogyasri.telangana.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
  {
    id: "dalit-bandhu-ts-025",
    schemeName: "Telangana Dalit Bandhu",
    ministry: "Scheduled Castes Development Department, Government of Telangana",
    benefitType: "livelihood",
    benefitAmount: "Livelihood assistance as notified by Telangana government",
    description: "Economic support for eligible SC households to start or strengthen livelihood units.",
    eligibility: {
      states: ["telangana"],
      categories: ["sc"],
      requiresAadhaar: true,
      requiresBankAccount: true,
    },
    keywords: ["sc", "dalit", "livelihood", "business", "telangana", "dalit bandhu", "self employment"],
    documentsRequired: ["Aadhaar Card", "Caste certificate", "Residence proof", "Bank account", "Livelihood unit proposal if requested"],
    applicationSteps: [
      "Contact local SC Development Department or district officials.",
      "Confirm whether applications or selection are open in your area.",
      "Submit identity, caste, residence, and bank details.",
      "Complete official selection, unit planning, and monitoring steps.",
    ],
    applicationUrl: "https://dalitbandhu.telangana.gov.in",
    applicationMode: "offline",
    sourceUrl: "https://dalitbandhu.telangana.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
  {
    id: "telangana-minority-scholarship-026",
    schemeName: "Telangana Minority Scholarships",
    ministry: "Minorities Welfare Department, Government of Telangana",
    benefitType: "scholarship",
    benefitAmount: "Scholarship amount varies by course and department rules",
    description: "Scholarship support for eligible minority students in Telangana through the ePASS channel.",
    eligibility: {
      occupations: ["student"],
      states: ["telangana"],
      categories: ["minority"],
      maxAnnualIncome: 200000,
      requiresAadhaar: true,
      requiresBankAccount: true,
    },
    keywords: ["student", "minority", "scholarship", "telangana", "epass", "education"],
    documentsRequired: ["Aadhaar Card", "Income certificate", "Minority/community certificate", "Bonafide certificate", "Bank account"],
    applicationSteps: [
      "Visit Telangana ePASS scholarship services.",
      "Select the relevant minority scholarship service.",
      "Submit course, income, community, and bank details.",
      "Track institute and department verification.",
    ],
    applicationUrl: "https://telanganaepass.cgg.gov.in",
    applicationMode: "online",
    sourceUrl: "https://telanganaepass.cgg.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
  {
    id: "ts-ipass-027",
    schemeName: "TG-iPASS / TS-iPASS",
    ministry: "Industries & Commerce Department, Government of Telangana",
    benefitType: "enterprise-clearance",
    benefitAmount: "Single-window industrial approvals; incentives depend on linked policy eligibility",
    description: "Single-window approval and self-certification system for Telangana industrial and service enterprises.",
    eligibility: {
      states: ["telangana"],
      occupations: ["entrepreneur", "small business", "self-employed"],
    },
    keywords: ["entrepreneur", "business", "industry", "telangana", "ipass", "msme", "approval"],
    documentsRequired: ["Business proposal", "Identity proof", "Land or premises details", "Project documents", "Approvals requested"],
    applicationSteps: [
      "Visit the TG-iPASS portal.",
      "Create entrepreneur or enterprise login.",
      "Select required approvals and submit project details.",
      "Track department processing through the portal.",
    ],
    applicationUrl: "https://ipass.telangana.gov.in",
    applicationMode: "online",
    sourceUrl: "https://ipass.telangana.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
  {
    id: "stree-nidhi-ts-028",
    schemeName: "Stree Nidhi Credit Cooperative Federation - Telangana",
    ministry: "Society for Elimination of Rural Poverty, Government of Telangana",
    benefitType: "loan",
    benefitAmount: "Credit support for self-help group members; amount varies by SHG and loan purpose",
    description: "Credit support channel for eligible women self-help group members in Telangana.",
    eligibility: {
      states: ["telangana"],
      genders: ["female"],
      occupations: ["entrepreneur", "small business", "self-employed", "tailoring", "artisan"],
      requiresBankAccount: true,
    },
    keywords: ["woman", "female", "self help group", "shg", "loan", "livelihood", "telangana", "stree nidhi"],
    documentsRequired: ["SHG membership details", "Identity proof", "Bank account", "Loan purpose details"],
    applicationSteps: [
      "Contact the local self-help group, VO, or SERP channel.",
      "Confirm SHG membership and credit eligibility.",
      "Submit loan purpose and bank details.",
      "Complete group and federation approval steps.",
    ],
    applicationUrl: "https://www.streenidhi.telangana.gov.in",
    applicationMode: "offline",
    sourceUrl: "https://www.streenidhi.telangana.gov.in",
    lastVerified: VERIFIED_ON,
    lastUpdated: VERIFIED_ON,
    stateScope: "telangana",
  },
];
