/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugIntegrationsRouteImport } from './routes/debug.integrations'
import { Route as ApiPrivacyDeleteRouteImport } from './routes/api/privacy/delete'

const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugIntegrationsRoute = DebugIntegrationsRouteImport.update({
  id: '/debug/integrations',
  path: '/debug/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivacyDeleteRoute = ApiPrivacyDeleteRouteImport.update({
  id: '/api/privacy/delete',
  path: '/api/privacy/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/architecture': typeof ArchitectureRoute
  '/schemes': typeof SchemesRoute
  '/debug/integrations': typeof DebugIntegrationsRoute
  '/api/privacy/delete': typeof ApiPrivacyDeleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/architecture': typeof ArchitectureRoute
  '/schemes': typeof SchemesRoute
  '/debug/integrations': typeof DebugIntegrationsRoute
  '/api/privacy/delete': typeof ApiPrivacyDeleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/architecture': typeof ArchitectureRoute
  '/schemes': typeof SchemesRoute
  '/debug/integrations': typeof DebugIntegrationsRoute
  '/api/privacy/delete': typeof ApiPrivacyDeleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/architecture'
    | '/schemes'
    | '/debug/integrations'
    | '/api/privacy/delete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/architecture'
    | '/schemes'
    | '/debug/integrations'
    | '/api/privacy/delete'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/architecture'
    | '/schemes'
    | '/debug/integrations'
    | '/api/privacy/delete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ArchitectureRoute: typeof ArchitectureRoute
  SchemesRoute: typeof SchemesRoute
  DebugIntegrationsRoute: typeof DebugIntegrationsRoute
  ApiPrivacyDeleteRoute: typeof ApiPrivacyDeleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/integrations': {
      id: '/debug/integrations'
      path: '/debug/integrations'
      fullPath: '/debug/integrations'
      preLoaderRoute: typeof DebugIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/privacy/delete': {
      id: '/api/privacy/delete'
      path: '/api/privacy/delete'
      fullPath: '/api/privacy/delete'
      preLoaderRoute: typeof ApiPrivacyDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ArchitectureRoute: ArchitectureRoute,
  SchemesRoute: SchemesRoute,
  DebugIntegrationsRoute: DebugIntegrationsRoute,
  ApiPrivacyDeleteRoute: ApiPrivacyDeleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
