
INSERT INTO public.schemes (id, scheme_name, ministry, benefit_type, benefit_amount, description, eligibility, keywords, documents_required, application_steps, application_url, application_mode, source_url, last_verified, state_scope) VALUES

('pm-kisan-001','PM-KISAN Samman Nidhi','Ministry of Agriculture & Farmers Welfare','cash','₹6,000/year in 3 instalments','Income support to all landholding farmer families across India.',
'{"occupations":["farmer"],"requiresAadhaar":true,"requiresBankAccount":true,"maxLandAcres":null}',
ARRAY['farmer','land','agriculture','income support','pm kisan'],
ARRAY['Aadhaar','Land records','Bank account','Ration card'],
ARRAY['Visit pmkisan.gov.in','Click Farmers Corner > New Farmer Registration','Enter Aadhaar and complete OTP','Fill land + bank details','Get status via Beneficiary Status link'],
'https://pmkisan.gov.in','online','https://pmkisan.gov.in','2026-06-01','central'),

('rythu-bandhu-ts-013','Rythu Bandhu — Telangana','Government of Telangana','cash','₹10,000/acre/year (₹5k per season)','Investment support to Telangana farmers per acre owned.',
'{"occupations":["farmer"],"states":["telangana"],"requiresAadhaar":true,"requiresBankAccount":true}',
ARRAY['farmer','telangana','rythu','investment','kharif','rabi'],
ARRAY['Pattadar passbook','Aadhaar','Bank passbook'],
ARRAY['Meet Village Revenue Officer with Pattadar passbook','Verify land records in RoR','Cheque disbursed at village mandal each season','Track at rythubandhu.telangana.gov.in'],
'https://rythubandhu.telangana.gov.in','offline','https://rythubandhu.telangana.gov.in','2026-06-15','telangana'),

('rythu-bima-ts-014','Rythu Bima — Telangana','Government of Telangana','insurance','₹5,00,000 life cover (fully paid)','Free life insurance for Telangana farmers aged 18–59.',
'{"occupations":["farmer"],"states":["telangana"],"minAge":18,"maxAge":59,"requiresBankAccount":true}',
ARRAY['farmer','insurance','telangana','life insurance','rythu bima'],
ARRAY['Aadhaar','Pattadar passbook','Nominee details'],
ARRAY['Automatic enrolment via Rythu Bandhu database','Submit nominee form at MRO office','Family claims via nominee on death'],
'https://rythubima.telangana.gov.in','offline','https://rythubima.telangana.gov.in','2026-06-15','telangana'),

('kcc-002','Kisan Credit Card','Ministry of Agriculture','loan','Up to ₹3,00,000 at 4% interest','Short-term credit for crop production and allied activities.',
'{"occupations":["farmer"],"requiresAadhaar":true,"requiresBankAccount":true}',
ARRAY['farmer','loan','credit','kcc','agriculture credit'],
ARRAY['Aadhaar','Land records','Bank passbook','Passport photo'],
ARRAY['Visit nearest bank branch','Fill KCC application form','Submit land + Aadhaar docs','Get card issued within 15 days','Repay after crop harvest'],
'https://www.pmkisan.gov.in/Documents/Kcc.pdf','offline','https://www.myscheme.gov.in/schemes/kcc','2026-05-20','central'),

('pmfby-003','Pradhan Mantri Fasal Bima Yojana','Ministry of Agriculture','insurance','Up to ₹2,00,000/hectare crop cover','Crop insurance against natural calamities, pests, and disease.',
'{"occupations":["farmer"],"requiresAadhaar":true,"requiresBankAccount":true}',
ARRAY['farmer','crop insurance','fasal bima','pmfby'],
ARRAY['Aadhaar','Land records','Sowing certificate','Bank account'],
ARRAY['Visit pmfby.gov.in or bank/CSC','Enter crop and land details','Pay 2% premium for Kharif / 1.5% Rabi','Retain policy number','File claim within 72 hours of loss'],
'https://pmfby.gov.in','online','https://pmfby.gov.in','2026-06-01','central'),

('pmay-g-004','Pradhan Mantri Awas Yojana — Gramin','Ministry of Rural Development','subsidy','₹1,20,000 (plain) / ₹1,30,000 (hilly) housing assistance','Pucca house for rural houseless / kutcha house families.',
'{"requiresAadhaar":true,"requiresBankAccount":true,"requiresBPL":false,"maxAnnualIncome":300000}',
ARRAY['housing','rural','awas','pmay','ghar'],
ARRAY['Aadhaar','Bank account','SECC data verification','Job card if MGNREGA'],
ARRAY['Gram Sabha selects eligible households from SECC list','Fill application at Panchayat','Track at pmayg.nic.in','Instalments credited on construction milestones'],
'https://pmayg.nic.in','offline','https://pmayg.nic.in','2026-05-15','central'),

('ayushman-005','Ayushman Bharat — PM-JAY','Ministry of Health','insurance','₹5,00,000/family/year cashless treatment','Health cover for secondary and tertiary hospitalisation.',
'{"maxAnnualIncome":800000,"requiresAadhaar":true}',
ARRAY['health','insurance','ayushman','pmjay','hospital','medical'],
ARRAY['Aadhaar','Ration card','Family ID'],
ARRAY['Check eligibility at pmjay.gov.in','Visit CSC or empanelled hospital','Get Ayushman card generated','Use at any 26,000+ empanelled hospitals'],
'https://pmjay.gov.in','both','https://pmjay.gov.in','2026-06-20','central'),

('mudra-006','Pradhan Mantri Mudra Yojana','Ministry of Finance','loan','Shishu ₹50k / Kishore ₹5L / Tarun ₹10L','Collateral-free micro-loans for non-farm micro-enterprises.',
'{"minAge":18,"occupations":["entrepreneur","small business","self-employed"]}',
ARRAY['loan','business','entrepreneur','mudra','micro loan','startup','tiffin','shop'],
ARRAY['Aadhaar','PAN','Business proof','6-month bank statement','Passport photo'],
ARRAY['Approach any bank / MFI / NBFC','Fill Mudra loan form + business plan','Choose Shishu/Kishore/Tarun','Get disbursement in 7–15 days'],
'https://www.mudra.org.in','both','https://www.mudra.org.in','2026-06-10','central'),

('svanidhi-007','PM SVANidhi','Ministry of Housing & Urban Affairs','loan','₹10,000 → ₹20,000 → ₹50,000 tiered working capital','Micro-credit for urban street vendors.',
'{"occupations":["street vendor","hawker"],"minAge":18}',
ARRAY['vendor','street vendor','urban','svanidhi','hawker','loan'],
ARRAY['Aadhaar','Vendor Certificate / LoR from ULB','Bank account'],
ARRAY['Get Vendor Certificate from ULB','Apply at pmsvanidhi.mohua.gov.in','Bank sanctions loan in 7 days','Repay in 12 monthly instalments'],
'https://pmsvanidhi.mohua.gov.in','online','https://pmsvanidhi.mohua.gov.in','2026-05-30','central'),

('stand-up-008','Stand-Up India','Ministry of Finance','loan','₹10 lakh – ₹1 crore','Bank loans for SC/ST and women entrepreneurs starting greenfield ventures.',
'{"minAge":18,"categories":["sc","st","general"],"genders":["female"],"occupations":["entrepreneur"]}',
ARRAY['entrepreneur','women','sc','st','stand up india','greenfield','business loan'],
ARRAY['Aadhaar','PAN','Business plan','Caste certificate (if SC/ST)','Bank statements'],
ARRAY['Register at standupmitra.in','Get connected to nearest scheduled bank','Submit project report','Loan sanctioned in 4–8 weeks'],
'https://www.standupmitra.in','online','https://www.standupmitra.in','2026-06-05','central'),

('pmkvy-009','PMKVY 4.0','Ministry of Skill Development','employment','Free training + ₹8,000 placement incentive','Short-term skill training with placement support for youth 15–45.',
'{"minAge":15,"maxAge":45}',
ARRAY['skill','training','youth','pmkvy','unemployed','job','placement'],
ARRAY['Aadhaar','Class 10 marksheet (if any)','Bank account'],
ARRAY['Find nearest PMKVY centre at pmkvyofficial.org','Choose sector + course','Complete 200–600 hour training','Get certified + placement support'],
'https://www.pmkvyofficial.org','both','https://www.pmkvyofficial.org','2026-05-25','central'),

('nsp-scholarship-010','National Scholarship Portal — Post-Matric','Ministry of Social Justice','scholarship','₹3,000 – ₹1,20,000/year','Post-matric scholarships for SC/ST/OBC/Minority students.',
'{"categories":["sc","st","obc","minority"],"minAge":15,"maxAge":30,"maxAnnualIncome":250000,"occupations":["student"]}',
ARRAY['student','scholarship','sc','st','obc','minority','nsp','education'],
ARRAY['Aadhaar','Income certificate','Caste certificate','Bank passbook','Institution fee receipt'],
ARRAY['Register at scholarships.gov.in','Fill Post-Matric application','Institution verifies','DBT to student bank account'],
'https://scholarships.gov.in','online','https://scholarships.gov.in','2026-06-01','central'),

('ts-fee-reimb-011','TS Post-Matric Fee Reimbursement','Government of Telangana','scholarship','Full tuition + ₹1,500/month maintenance','Tuition fee reimbursement + mess charges for TS SC/ST/BC/EBC/Minority students.',
'{"states":["telangana"],"categories":["sc","st","obc","minority","ebc"],"maxAnnualIncome":250000,"occupations":["student"]}',
ARRAY['student','telangana','fee reimbursement','sc','st','bc','ebc','tuition'],
ARRAY['Aadhaar','TS Income certificate','Caste certificate','Bonafide certificate','Bank passbook'],
ARRAY['Register at telanganaepass.cgg.gov.in','Fill Post-Matric application before Oct 31','College verifies','Amount released to college + student'],
'https://telanganaepass.cgg.gov.in','online','https://telanganaepass.cgg.gov.in','2026-06-15','telangana'),

('aasara-012','Aasara Pension — Telangana','Government of Telangana','cash','₹2,016/month (old age / widow / disability) / ₹3,016 (single women)','Monthly social security pension for vulnerable TS residents.',
'{"states":["telangana"],"minAge":57,"maxAnnualIncome":150000,"requiresBankAccount":true}',
ARRAY['pension','elderly','widow','disability','telangana','aasara','old age'],
ARRAY['Aadhaar','Bank passbook','Age proof','Widow/Disability certificate (if applicable)'],
ARRAY['Visit Mandal Revenue Office','Submit application form + docs','MRO verifies + approves','Pension credited monthly to bank'],
'https://aasara.telangana.gov.in','offline','https://aasara.telangana.gov.in','2026-06-15','telangana'),

('kalyana-lakshmi-015','Kalyana Lakshmi — Telangana','Government of Telangana','cash','₹1,00,116 one-time','One-time marriage assistance for SC/ST/BC/EBC/Minority brides in Telangana.',
'{"states":["telangana"],"categories":["sc","st","obc","minority","ebc"],"genders":["female"],"minAge":18,"maxAnnualIncome":200000}',
ARRAY['marriage','bride','telangana','kalyana lakshmi','shaadi mubarak'],
ARRAY['Aadhaar','Income certificate','Caste certificate','Marriage card','Bank passbook'],
ARRAY['Apply at telanganaepass.cgg.gov.in/KalyanaLakshmi','Submit before or within 1 month of marriage','MRO verifies','Amount credited to bride'],
'https://telanganaepass.cgg.gov.in','online','https://telanganaepass.cgg.gov.in','2026-06-15','telangana'),

('ujjwala-016','PM Ujjwala Yojana 2.0','Ministry of Petroleum','subsidy','Free LPG connection + first refill','Free LPG connection for women from BPL / vulnerable households.',
'{"genders":["female"],"requiresBPL":false,"maxAnnualIncome":200000,"requiresAadhaar":true}',
ARRAY['lpg','gas','women','ujjwala','cooking','fuel'],
ARRAY['Aadhaar','Ration card / self-declaration','Bank account'],
ARRAY['Visit nearest LPG distributor','Fill KYC form','Get free connection + stove','First refill free'],
'https://www.pmuy.gov.in','offline','https://www.pmuy.gov.in','2026-05-30','central'),

('jan-dhan-017','PM Jan Dhan Yojana','Ministry of Finance','other','Zero-balance account + ₹2L accident cover','Financial inclusion — bank account for every household.',
'{"minAge":10,"requiresAadhaar":true}',
ARRAY['bank account','financial inclusion','jan dhan','zero balance'],
ARRAY['Aadhaar or any officially valid document'],
ARRAY['Visit any bank branch or Bank Mitra','Fill PMJDY form','Get RuPay debit card + passbook','Activate mobile banking'],
'https://pmjdy.gov.in','offline','https://pmjdy.gov.in','2026-05-15','central'),

('apy-018','Atal Pension Yojana','PFRDA','other','₹1,000 – ₹5,000 guaranteed monthly pension after 60','Guaranteed pension scheme for unorganised sector workers.',
'{"minAge":18,"maxAge":40,"requiresBankAccount":true,"requiresAadhaar":true}',
ARRAY['pension','apy','atal','unorganised','retirement'],
ARRAY['Aadhaar','Bank account','Mobile number'],
ARRAY['Visit your bank branch','Fill APY registration form','Auto-debit set up from savings account','Pension after age 60'],
'https://npscra.nsdl.co.in/scheme-details.php','offline','https://www.india.gov.in/spotlight/atal-pension-yojana','2026-05-20','central'),

('sukanya-019','Sukanya Samriddhi Yojana','Ministry of Finance','other','Currently 8.2% p.a., tax-free','Long-term savings for girl child under 10.',
'{"genders":["female"],"maxAge":10,"requiresAadhaar":true,"requiresBankAccount":true}',
ARRAY['girl child','savings','sukanya','education','daughter'],
ARRAY['Girl child birth certificate','Parent/guardian Aadhaar','Bank/post office account'],
ARRAY['Visit post office or authorised bank','Fill SSY form for girl below 10','Deposit ₹250–₹1.5L per year','Matures at 21 or on marriage after 18'],
'https://www.nsiindia.gov.in/InternalPage.aspx?Id_Pk=89','offline','https://www.nsiindia.gov.in/InternalPage.aspx?Id_Pk=89','2026-05-10','central'),

('ebc-loan-020','TS EBC Overseas Study Scheme','Government of Telangana','scholarship','Up to ₹20 lakh for overseas study','Financial assistance to EBC students for postgraduate study abroad.',
'{"states":["telangana"],"categories":["ebc","general"],"minAge":18,"maxAge":35,"maxAnnualIncome":500000,"occupations":["student"]}',
ARRAY['overseas','study abroad','ebc','telangana','higher education'],
ARRAY['Passport','I-20 / offer letter','Aadhaar','Income certificate','Academic records'],
ARRAY['Apply at bcwtsonline.telangana.gov.in','Upload offer + documents','Interview at BC Welfare','Amount sanctioned pre-departure'],
'https://bcwtsonline.telangana.gov.in','online','https://bcwtsonline.telangana.gov.in','2026-06-01','telangana'),

('nrega-021','MGNREGA Job Card','Ministry of Rural Development','employment','100 days guaranteed wage employment/year','Guaranteed rural employment scheme.',
'{"minAge":18}',
ARRAY['job','employment','rural','mgnrega','nrega','wage'],
ARRAY['Aadhaar','Ration card','Passport photo'],
ARRAY['Apply at Gram Panchayat','Job card issued in 15 days','Demand work in writing','Get wages within 15 days of work'],
'https://nrega.nic.in','offline','https://nrega.nic.in','2026-05-01','central'),

('mission-shakti-022','Mission Shakti — Working Women Hostels','Ministry of Women & Child Development','subsidy','Subsidised safe accommodation','Safe hostels + daycare for working women.',
'{"genders":["female"],"occupations":["employed","student"],"minAge":18}',
ARRAY['women','hostel','working women','safe','mission shakti'],
ARRAY['ID proof','Employment/College proof','Income proof'],
ARRAY['Locate hostel via wcd.nic.in','Apply at hostel warden office','Provide employer/institution letter','Move in on approval'],
'https://wcd.nic.in','offline','https://wcd.nic.in','2026-04-20','central'),

('mgnss-023','Maulana Azad National Scholarship','Ministry of Minority Affairs','scholarship','₹20,000/year for M.Phil, ₹25,000 for PhD','Fellowship for minority community research scholars.',
'{"categories":["minority"],"maxAge":35,"maxAnnualIncome":600000,"occupations":["student"]}',
ARRAY['minority','scholarship','muslim','christian','sikh','phd','research'],
ARRAY['Aadhaar','Income certificate','Minority certificate','Admission proof'],
ARRAY['Register on UGC portal','Apply via NSP','Institute verifies','Fellowship disbursed monthly'],
'https://scholarships.gov.in','online','https://scholarships.gov.in','2026-05-25','central'),

('nirmaan-024','TS Building & Other Construction Workers Welfare','Government of Telangana','other','Health, marriage, education & death benefits','Welfare fund benefits for registered construction workers.',
'{"states":["telangana"],"occupations":["construction worker","daily wage"],"minAge":18,"maxAge":60}',
ARRAY['construction','worker','telangana','labour','building','nirmaan'],
ARRAY['Aadhaar','90-day work certificate','Bank passbook'],
ARRAY['Register at any Labour Office','Pay ₹50 annual fee','Get identity card','Claim scheme-wise benefits'],
'https://labour.telangana.gov.in','offline','https://labour.telangana.gov.in','2026-06-01','telangana'),

('divyangjan-025','Unique Disability ID (UDID) + Assistance','Ministry of Social Justice','other','ID + disability pension + assistive devices','National ID enabling multiple benefits for Persons with Disabilities.',
'{"requiresAadhaar":true,"disability":true}',
ARRAY['disability','divyang','udid','pwd','assistive'],
ARRAY['Aadhaar','Disability certificate','Passport photo','Address proof'],
ARRAY['Apply at swavlambancard.gov.in','Get medical assessment at CMO','Receive UDID card','Use for all PwD scheme claims'],
'https://swavlambancard.gov.in','online','https://swavlambancard.gov.in','2026-05-15','central'),

('nfsa-026','National Food Security Act — Ration','Department of Food & Public Distribution','subsidy','5 kg foodgrain/person/month at ₹1–₹3/kg','Subsidised foodgrains via PDS.',
'{"maxAnnualIncome":180000,"requiresAadhaar":true}',
ARRAY['ration','food','pds','nfsa','antyodaya','bpl'],
ARRAY['Aadhaar','Address proof','Income declaration'],
ARRAY['Apply at nearest FPS / Civil Supplies office','Get ration card issued','Collect monthly quota with biometric'],
'https://nfsa.gov.in','offline','https://nfsa.gov.in','2026-05-10','central'),

('pmjjby-027','PM Jeevan Jyoti Bima Yojana','Ministry of Finance','insurance','₹2,00,000 life cover for ₹436/year','Term life insurance for savings account holders 18–50.',
'{"minAge":18,"maxAge":50,"requiresBankAccount":true}',
ARRAY['life insurance','pmjjby','term insurance','affordable'],
ARRAY['Aadhaar linked to bank account'],
ARRAY['Visit your bank branch or netbanking','Consent to PMJJBY enrolment','₹436 auto-debited annually','Nominee claims on death'],
'https://www.jansuraksha.gov.in','online','https://www.jansuraksha.gov.in','2026-05-20','central'),

('pmsby-028','PM Suraksha Bima Yojana','Ministry of Finance','insurance','₹2L accident cover for ₹20/year','Accident insurance for bank account holders 18–70.',
'{"minAge":18,"maxAge":70,"requiresBankAccount":true}',
ARRAY['accident','insurance','pmsby','affordable'],
ARRAY['Aadhaar linked to bank account'],
ARRAY['Enrol at bank or netbanking','₹20 auto-debited annually','Cover from 1 June to 31 May','Claim via bank on accident'],
'https://www.jansuraksha.gov.in','online','https://www.jansuraksha.gov.in','2026-05-20','central');
